package agentarium.multithreading;

public enum RequestType {
    ALL_WORKERS_FINISH_TICK,
    ALL_WORKERS_UPDATE_COORDINATOR,
    AGENT_ACCESS,
    FILTERED_AGENTS_ACCESS,
    MODEL_ATTRIBUTES_ACCESS,
    UPDATE_COORDINATOR_AGENTS
}
